### ISSUE TITLE
Perfomance issue when editing

### ISSUE THREAD

**Issue by dapozdnyakov** [DevExpress/devextreme-reactive#353]
I'm using code example from material-ui/editing/edit-row-controlled.jsx with my custom data (20 rows, 7 cols).  In row edit mode when I type a symbol it takes ~0.5 sec to be shown in input. When I check "Highlight Updates" in react developer tools in chrome, I see that with every typed symbols the whole grid is updated.

What can be the cause? Thanks in advance.

**Comment by kvet** [comment]
Hi,

Thank you for bringing this to our attention. I've reproduced the issue. The problem is in our theme plugin. Please take a look at the example: https://github.com/DevExpress/devextreme-reactive/blob/v1.0.0-alpha.10/packages/dx-react-grid-material-ui/src/plugins/table-view.jsx. As you can see, we use a stateless component that generates new templates each time the component is rendered. To resolve the issue, it is necessary to use pure components to prevent redundant rendering. At the moment, there is no option to overcome this behavior until we fix it on our side. We will do our best to fix it as soon as possible. Please bear with us.

**Comment by kvet** [comment]
Hi,

We have released the 1.0.0-alpha.11 version of React Grid containing fixes related to the issue.

**Comment by dapozdnyakov** [comment]
Hi!
Upgraded components to 1.0.0-alpha.11, but still getting the same issue:
![react-dx-grid](https://user-images.githubusercontent.com/23720988/31389054-8caa0c84-add8-11e7-9902-40c65047de83.png)

**Comment by kvet** [comment]
Hi, @dapozdnyakov,
 
From what I gather, you are using our Grid in controlled mode. If so, please refer to the following demos:
 
- A demo with a function declared in the `render` method (https://stackblitz.com/edit/react-rpbisq?file=index.js)
- A demo with a function defined outside the `render` method declaration (https://stackblitz.com/edit/react-64a7zg?file=index.js) 
 
Take note of how the performance differs in the demos. So, avoid declaring data and functions in the `render` method. See also: https://reactjs.org/docs/optimizing-performance.html
 
If the described solution does not address the issue, please provide us with a simple example demonstrating the problem. Your time and cooperation are greatly appreciated.

**Comment by dapozdnyakov** [comment]
@kvet 
Thank you, the problem was exactly in getRowId.
But I've found similar issue with selection: when a row is selected the entire grid is updated.

**Comment by kvet** [comment]
@dapozdnyakov,

I could not reproduce the issue. In the following example, SelectionState and TableSelection plugins are used. Grid is not updated entirely, only selection cells are. I don't see major performance impact. Here is an example: https://stackblitz.com/edit/react-srzprk?file=index.js

**Comment by dapozdnyakov** [comment]
@kvet 
It reproduces in https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-demos/src/material-ui/selection/hidden-checkboxes.jsx

**Comment by kvet** [comment]
@dapozdnyakov,

I've reproduced the problem and created a separate issue. You can track our progress here: https://github.com/DevExpress/devextreme-reactive/issues/397

**Comment by dapozdnyakov** [comment]
@kvet Thank you!
Offtop: When virtual scrolling for material-ui is planed to be implemented?

**Comment by kvet** [comment]
@dapozdnyakov,

We have plans to implement it soon.
