### ISSUE TITLE
Support column virtualisation

### ISSUE THREAD

**Issue by kvet** [DevExpress/devextreme-reactive#853]
Support column virtualisation in the VirtualTable plugin. It will allow increasing scrolling performance in scenarios where there are multiple records with many columns that are not visible in the table viewport.

**Comment by kvet** [comment]
We've just released Rect Grid [v1.2.0-beta.2](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#1.2.0-beta.2). This release contains column virtualization support. Well, you can check it out and give us your feedback, if any. Here the link to the beta version of the site: https://devexpress.github.io/devextreme-reactive/@next/

**Comment by RahavLussato** [comment]
@kvet thanks, i'll play with it and get back to you

**Comment by RahavLussato** [comment]
@kvet after playing with it, its works better now i still have a bit laggish scrolling (now its may needed more optimisations from my side).
the only thing that i think it worth to write it in the docs is that if you using wrapping the row component like the example of virtual scrolling (to control the onShow) and using shouldComponentUpdate, now you should also check the this.props.children and nextProps.children too see if there is any change to the rendered columns.

**Comment by kvet** [comment]
@RahavLussato, thank you for checking it.

I've recently posted another solution for a hook for loading more rows in the virtual table: #882. It may improve performance as well

**Comment by kvet** [comment]
We've released the [1.2.0](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.2.0) version containing described changes.
